### ISSUE TITLE
express導入

### ISSUE THREAD

**Issue by jumtech** [zuckeyM-17/shiganai-radio-page#32]
https://github.com/angular/angular-cli/issues/5852#issuecomment-292485068

https://github.com/ngx-meta/core
↑のモジュールに切り替える.

**Comment by jumtech** [comment]
SSR前提っぽい...

**Comment by jumtech** [comment]
結局、expressを導入することになった.

**Comment by jumtech** [comment]
参考記事
https://scotch.io/tutorials/mean-app-with-angular-2-and-the-angular-cli

**Comment by jumtech** [comment]
Angular4から、Metaが使えるようになっていた...
https://blog.lacolaco.net/post/ng4-feature-meta-service/
expressやめる.

**Comment by jumtech** [comment]
ところがどっこい、やはりbotにはJSを実行するのが難しいらしい.
https://stackoverflow.com/questions/23669640/single-page-application-cant-get-current-page-meta-tag-for-facebook-share
http://www.michaelbromley.co.uk/blog/171/enable-rich-social-sharing-in-your-angularjs-app#_section-the-solution
やはり、サーバーサイドが無いといけない模様.

SSRをするか、サーバー側でテンプレートエンジンを使うかする.

**Comment by jumtech** [comment]
Angular4のSSRを解説する神サイトを見つけたので、真似する.
https://coursetro.com/posts/code/68/Make-your-Angular-App-SEO-Friendly-(Angular-4-+-Universal)

**Comment by jumtech** [comment]
```
> ts-node src/server.ts
```
で以下のエラーが出る...
soundcloud sdkとSSRの相性？

```js
TypeError: Cannot read property 'getUserMedia' of undefined
    at Object.<anonymous> (/Users/jumpei/shiganai-radio-page/node_modules/soundcloud/sdk.js:8:14491)
    at Object.n (/Users/jumpei/shiganai-radio-page/node_modules/soundcloud/sdk.js:8:14621)
    at e (/Users/jumpei/shiganai-radio-page/node_modules/soundcloud/sdk.js:1:352)
    at Object.<anonymous> (/Users/jumpei/shiganai-radio-page/node_modules/soundcloud/sdk.js:8:15038)
    at e (/Users/jumpei/shiganai-radio-page/node_modules/soundcloud/sdk.js:1:352)
    at Object.<anonymous> (/Users/jumpei/shiganai-radio-page/node_modules/soundcloud/sdk.js:1:537)
    at Object.q (/Users/jumpei/shiganai-radio-page/node_modules/soundcloud/sdk.js:1:1347)
    at e (/Users/jumpei/shiganai-radio-page/node_modules/soundcloud/sdk.js:1:352)
    at /Users/jumpei/shiganai-radio-page/node_modules/soundcloud/sdk.js:1:439
    at /Users/jumpei/shiganai-radio-page/node_modules/soundcloud/sdk.js:1:444
```

**Comment by jumtech** [comment]
episodeservice周りのコードを一旦コメントアウトしたら、コマンドは通った.

http://localhost:4000/ にアクセスしたが、
`og:url`取得用の`document.location.origin`でエラー.
そりゃそうだ.
